name: Say Hello!
run-name: Running Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "Hello Jorge World"
      - name: Give me Date
        run: date
      - name: Give me directory content
        run: ls -l
