name: Say Hello!
run-name: Running Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo message
        run: echo "Hello Jorge World"
