name: CI - Verify on dev branch
run-name: This workflow will check that the code is OK before merging it with main branch
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      - name: Verificar linting
        run: npm run lint

      - name: Construcción de prueba
        run: npm run build
